export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';
export const CHECK_ANSWER = "CHECK_ANSWER";
export const SET_BEGIN = "SET_BEGIN"

